### ISSUE TITLE
Led Count | only 40 Leds lighting

### ISSUE THREAD

**Issue by Yohan54** [mathfarmer/ColorOrgan_Arduino_Serial#1]
Hi,

Using your Arduino Neo_Pixel and the ColorOrgan_Arduino processing code. The leds that I am using is a 60LED 1m strip of WS2812B. The code works fine for the most part, the end of the strip, led's are not lighting. The first 40 led's are lighting to the beat of music. Is it just limitation of the 12 band that is set in the code.

**Comment by mathfarmer** [comment]
No, that's just a constant set in the Arduino sketch. Change
`#define LED_COUNT       40`
to
`#define LED_COUNT       60`
upload to the Arduino again, and it should light all 60 LEDs.

**Comment by mathfarmer** [comment]
Hmm...it looks like I may have hardcoded 40 instead of using the constant. Hold on...

**Comment by mathfarmer** [comment]
Can you try changing line 87 to this:

``` C
Adafruit_NeoPixel strip = Adafruit_NeoPixel(LED_COUNT, PIN, NEO_GRB + NEO_KHZ800);
```

If that works, let me know and I'll patch the repo (or you can submit a PR if you would like).

**Comment by Yohan54** [comment]
All good now. I somehow missed the hard code value in the sketch. Made the suggested line change, You can go ahead patch the repo.
Thanks for the help and the code. 

```
  From: mathfarmer <notifications@github.com>
```

 To: mathfarmer/ColorOrgan_Arduino_Serial ColorOrgan_Arduino_Serial@noreply.github.com 
Cc: Yohan54 jl31m10@yahoo.com; Author author@noreply.github.com
 Sent: Saturday, June 11, 2016 3:24 PM
 Subject: Re: [mathfarmer/ColorOrgan_Arduino_Serial] Led Count | only 40 Leds lighting (#1)

Can you try changing line 87 to this:
Adafruit_NeoPixel strip = Adafruit_NeoPixel(LED_COUNT, PIN, NEO_GRB + NEO_KHZ800);
If that works, let me know and I'll patch the repo (or you can submit a PR if you would like).—

**Comment by mathfarmer** [comment]
Thanks for the report--I only tested with one strip, so I missed that I had done that.
